services:
  - type: web
    name: cafe-recs-backend
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
