services:
  - type: web
    name: cafe-recs-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cafe-recs-db
          property: connectionString
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
databases:
  - name: cafe-recs-db
    plan: basic-256mb
    region: oregon
