const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
dotenv.config();

const sample = [
  {
    name: 'BROWN Roastery | BKK',
    description: 'Specialty coffee roastery in BKK1',
    tags: ['specialty coffee'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://www.google.com/maps/place/%E1%9E%94%E1%9F%92%E1%9E%9A%E1%9F%84%E1%9E%93%E1%9E%9A%E1%9F%89%E1%9E%BC%E1%9E%9F%E1%9F%92%E1%9E%91%E1%9E%BA%E1%9E%9A%E1%9E%B8+%E1%9E%94%E1%9E%B9%E1%9E%84%E1%9E%80%E1%9F%81%E1%9E%84%E1%9E%80%E1%9E%84/@11.5533985,104.924819,3a,75y,90t/data=!3m8!1e2!3m6!1sCIABIhA-J8W2atO_fjuR7VnDaYeD!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAPNQkAFLfYZxQ2huBxx0o9PiPmmrLwpHfaS89FPcHGW7UIXQd-NCRGUM6LbApRtt4DRmcAdjFjRMef4h3V2cuXndHT8vOy0zJGgIjAOeSpfVVNhcnUfbH0xwfrqMbgc2eyZeRiOn51mbP1Ow7luy%3Dw203-h270-k-no!7i3024!8i4032!4m11!1m2!2m1!1sBROWN+Roastery+%7C+BKK+BKK1,+Phnom+Penh!3m7!1s0x310951252586ffa1:0x4052be2c82c7a733!8m2!3d11.5532865!4d104.9248357!10e5!15sCiVCUk9XTiBSb2FzdGVyeSB8IEJLSyBCS0sxLCBQaG5vbSBQZW5oIgOIAQFaJCIiYnJvd24gcm9hc3RlcnkgYmtrIGJrazEgcGhub20gcGVuaJIBC2NvZmZlZV9zaG9wmgFEQ2k5RFFVbFJRVU52WkVOb2RIbGpSamx2VDJ0MFdXVnFaR3RYYTFwM1UwWkNVbFo2YUROV2FrcFVVVzFuZDAxclJSQULgAQD6AQQIABAb!16s%2Fg%2F11xf48rnf?entry=ttu&g_ep=EgoyMDI2MDUxMy4wIKXMDSoASAFQAw%3D%3D#'],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 90,
    isOpen: true
  },
  {
    name: 'Java Creative Cafe Toul Kork',
    description: 'Creative cafe in Toul Kork district',
    tags: ['cafe', 'creative'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEcvuqyB_G5FngwYVxRIUQrIKG6qtH7uIu8LBprj8r8QCysMIXz_H6EcWOXM8wsO5ZW5Y1lVKhBTeHENwSjXclc2tFs8B5kW9ZAxKMZ0CnMFpjFPK9CqwYT8zQB9dh_rQ6cDbb5=w426-h240-k-no  '],
    location: { address: 'Tuol Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 75,
    isOpen: true
  },
  {
    name: 'Backyard Cafe',
    description: 'Healthy cafe with nutritious options',
    tags: ['healthy cafe', 'organic'],
    facilities: ['WiFi', 'Seating', 'Outdoor area'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEcFLTk-uEHqxgUA3iozuHrVNlHROqVnzL9EDMdwfndJshfKZT4CUaXM5b3dIRr5-XaviLRx6mDGbKdUEEgPT2x7GWuoySxlPrghrGFIgurfaj9VtmNE3J_4XJUqx_gNKBjc9HCZmTGeTpE=w408-h271-k-no'],
    location: { address: 'Daun Penh, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 85,
    isOpen: true
  },
  {
    name: 'Starbucks BKK1 Phnom Penh',
    description: 'Premium coffee chain',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.2,
    priceLevel: 3,
    wifiSpeed: 70,
    images: ['https://maps.app.goo.gl/1VtXMBNh7cXxR88Z9'],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 95,
    isOpen: true
  },
  {
    name: 'Feel Good Coffee (Phnom Penh)',
    description: 'Premium specialty coffee with excellent WiFi',
    tags: ['specialty coffee', 'premium'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 5.0,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAElUAPCAZ3WFxuvpT04HeZ9D8x8IxB5Bj6Sa-kBQ9bFuj-T247TxHqnxiPLd0UyDmoLLMbTp3fNEIXuKp-EsOOUh_OmvYcVeOxl5ZxKv-W66ekZ6rlZm5HVqAa5LyqEUx3KeQJD6FFL26Y=w408-h272-k-no'],
    location: { address: 'Chamkar Mon, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 92,
    isOpen: true
  },
  {
    name: 'Living Room',
    description: 'Comfortable and spacious cafe',
    tags: ['cafe', 'relaxing'],
    facilities: ['WiFi', 'Seating', 'Comfortable'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHt-NsC8yqTM-mX25Od8Ii30MgS22zxpdXB0TQ5fpgMbeOuHcNTLtIVDkFg5eNRhI2JOSOY0uAyhJgAGsXIR1oBUJk2u6WsM_DmGnD9og-Al8vJmfoQgIfWWxV_71hondUJAQir8yhu3L42=w426-h240-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'Market Café Restaurant & Lounge',
    description: 'Upscale cafe and restaurant',
    tags: ['cafe', 'restaurant'],
    facilities: ['WiFi', 'Seating', 'Lounge'],
    rating: 4.5,
    priceLevel: 3,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFsi3aSsLCJUXCZLJFDzXkntQIinJyhX0Bxkmr6rY-2nT8N7NjZCXyNKgidQx6gwSW-VEDUw6hY6WkdbJ-EEaP3GrtgmCoMXs1-EkkkOIt27QnuIyaU_B8zb73nb2QEGwwa6pMi=w408-h272-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'Phnom Penh Three Rivers Restaurant',
    description: 'Restaurant with scenic views',
    tags: ['restaurant', 'scenic'],
    facilities: ['Seating', 'Restaurant'],
    rating: 3.9,
    priceLevel: 2,
    wifiSpeed: 60,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFpXrif06fRo940nDrmwxtWbmeolC840RMAetglUO4-sWd_R4bc-8AgXjEwZgIuJt7-mUe-MJMyEhMfa2TxFhcZLESYYjSvYMIyqkc0WRkG5PaKV5dqvLeqr-LZ5kC09WHBwjW9MVU3W-kv=w408-h544-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 70,
    isOpen: true
  },
  {
    name: 'La. Chronique Cafe & Bistro',
    description: 'French-inspired cafe and bistro',
    tags: ['cafe', 'bistro', 'french'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.7,
    priceLevel: 3,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFFEJ9UzRaKcztYRaHHSlj-XMKksUll6VYjJO_5w1YTahmqr2xhtCBKSJfvPOlbwin6_sUPXkMfgPhQEpowqO8dBH37CoHrlK7VS8nFeOMjx9o2hwu8TYp1i33oVtd5hcspyY3xYA=w408-h271-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 72,
    isOpen: true
  },
  {
    name: 'The Barista',
    description: 'Professional barista cafe',
    tags: ['cafe', 'specialty coffee'],
    facilities: ['Seating', 'Professional Coffee'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 0,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEnfj7zscGYXpa1M8V1rqqtGDZJKBDZCvNE_JIeHtsgbgPX_iblXiIam_g3LbiZDdYV-ijTUVlMhcP5kXmAe9nWb217qupSc6e5E2Y29S0L3zP9DePFzZycMcS0u7dNwGMFbScVyYPepMSN=w408-h408-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 75,
    isOpen: true
  },
  {
    name: 'Socials - Coffee and Humanity',
    description: 'Community-focused cafe',
    tags: ['cafe', 'community'],
    facilities: ['Seating', 'Community Space'],
    rating: 3.8,
    priceLevel: 1,
    wifiSpeed: 60,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 65,
    isOpen: true
  },
  {
    name: 'Nuk Cafe',
    description: 'Cozy neighborhood cafe with roastery',
    tags: ['cafe', 'roastery'],
    facilities: ['WiFi', 'Seating', 'Roastery'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFzoNCf5jJUd-f915W-BMTFM0DNCfBXib-5K4UFcUrmr4IcgXFutt8vgkdnpQpGexvMjWL_PEgU1xRAuoRlLV2WAttJ_-rxrS1z2jiDtmRLc4r3emVyIl0bmpfQDuLdsXxB64eWydCi52zg=w408-h306-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'GW Cafe',
    description: 'Casual neighborhood cafe',
    tags: ['cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.8,
    priceLevel: 1,
    wifiSpeed: 60,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEcvuqyB_G5FngwYVxRIUQrIKG6qtH7uIu8LBprj8r8QCysMIXz_H6EcWOXM8wsO5ZW5Y1lVKhBTeHENwSjXclc2tFs8B5kW9ZAxKMZ0CnMFpjFPK9CqwYT8zQB9dh_rQ6cDbb5=w426-h240-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 68,
    isOpen: true
  },
  {
    name: 'Brown Cafe',
    description: 'Premium brown coffee experience',
    tags: ['cafe', 'premium'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.6,
    priceLevel: 2,
    wifiSpeed: 85,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGyhROusu-E6TiA7YvnYuLvin0bjcRIR58ho0GBGDvrIdPlmR6WDhhfiAHgY4jSoFcoWWI-N_qt7eiu4nr0cgEW6wzk_0KZVH9DQ8ofFTYsxGSas1K6vnknAI2bopl3bayBDPGgaUVwB07I=w408-h544-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 88,
    isOpen: true
  },
  {
    name: 'CHHMA Catfe',
    description: 'Cat-themed cafe in Chom Neas',
    tags: ['cafe', 'cat cafe'],
    facilities: ['WiFi', 'Seating', 'Cat Area'],
    rating: 4.6,
    priceLevel: 2,
    wifiSpeed: 90,
    images: ['https://www.google.com/maps/place/%E1%9E%86%E1%9F%92%E1%9E%98%E1%9E%B6%E1%9E%81%E1%9F%81%E1%9E%8F%E1%9E%A0%E1%9F%92%E1%9E%9C%E1%9F%81/@11.5669292,104.9312017,3a,75y,90t/data=!3m8!1e2!3m6!1sCIABIhCmkKjTTqA6bjidd3RPvkcC!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAPNQkAHO9MEA3wFpWSggG00UIrTdqBDhMpV1FTnfwlZpE1P6IxsDx-nCBuH3cT4jGursjFvgksK1J65Yb5NlbG03XEyoR0Dbe11HBl76bjzaQiaHjaKBQ89gxD10Izmx4wDASctHdn-N9r7YEfIW%3Dw203-h270-k-no!7i3024!8i4032!4m7!3m6!1s0x3109514a55c0e253:0xd9b8c8ed6411cd2c!8m2!3d11.5670183!4d104.9311882!10e5!16s%2Fg%2F11hdjh4jnq?entry=ttu&g_ep=EgoyMDI2MDUxMy4wIKXMDSoASAFQAw%3D%3D#'],
    location: { address: 'Chom Neas, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 87,
    isOpen: true
  },
  {
    name: 'WAT Chocolate',
    description: 'Chocolate and cafe experience',
    tags: ['cafe', 'chocolate'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 75,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAG0YFzwma9B-PoZ7-mTMLjDvaqS6LLrYSEtXJBqH9BpdrMxGHMpXrLGKj9zuc0nGfsCePNcM0Qo4CTZLSmGcwtCubLbFXzZjIJ20XyGuoKviwYBsfNc3VC9fkLsx0soWjBZw44T=w408-h328-k-no'],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 82,
    isOpen: true
  },
  {
    name: 'Museum Cafe',
    description: 'Cafe near cultural sites',
    tags: ['cafe', 'cultural'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAECrpaV3riZMOR-W_oYLLPZi-6VsX7IrcIc5Susf_HPFf9azWi-UHCa1lXMsUWQ1io_NVLEOKOO5FUyI-G99RA-fqEilfoa99a6Hie8L8mcoP5Viioa-xs0sHIBNxCRXicSsIbPSHOF6ag6=w408-h305-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 74,
    isOpen: true
  },
  {
    name: 'Cerise\'s Bakery & Coffee',
    description: 'Bakery with quality coffee',
    tags: ['bakery', 'coffee'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.1,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh5.googleusercontent.com/RHzJgVQulrDG91eCt2g10y1D6ucR0nw7PvqIE17LkDqoRs4j_MH1efRtXvroOA5KSQ=w426-h240-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'Brown Sothearos',
    description: 'Brown coffee at Sothearos location',
    tags: ['cafe', 'coffee'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGTzX9dB7jER4Cem4gd6XXJQR2DKBDlThLUnPB4PP_eH5P-KecSCk4Ta8J33j5y7rQ4zFq4xt3SU3Z9CLTSspCegON09tuQVCzrvV9ZbspM5XYCnCqQA05AWRQOg4F3hTfE9zoG=w408-h486-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'Gelatofix',
    description: 'Gelato and coffee',
    tags: ['cafe', 'gelato'],
    facilities: ['Seating'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 75,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGqkTS1tGZsDwcdgIj4xgNUPzAMdqSRKqmJzgABVqzMUltPouCKQFIjJlWoEkpP7yYh6B8wvVomKHtU7zOFU5R0HdxVvm5jN4hjHMJp8Rsm750KY0sVH7pK14oeOnncnUiQwpiIuexHF7U=w408-h306-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 71,
    isOpen: true
  },
  {
    name: 'TWG Tea at Vattanac Mall',
    description: 'Premium tea house',
    tags: ['tea', 'premium'],
    facilities: ['Seating', 'Air conditioning'],
    rating: 4.3,
    priceLevel: 3,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAF46gAZ1HeON4LbUySqRvDdFGLB0qvGSHhNfzu8Fqysq0N6z-YqW_pEcqkNTkxkAWwkc-Io36U693yJsflxAn7LYBA3_HksFR8GfDG3LC0NIFIjMLxXtaMtQbQqP69jkkyTQAD-=w408-h272-k-no'],
    location: { address: 'Vattanac Mall, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 77,
    isOpen: true
  },
  {
    name: 'Khmer Flower House Cafe',
    description: 'Traditional Khmer cafe with flowers',
    tags: ['cafe', 'khmer', 'cultural'],
    facilities: ['Seating', 'Garden'],
    rating: 4.9,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGSQXUkFSFKvUCDbuI7kGELMoul-pGbZoL29zQDNfikdi75YfRk9d3MdUuEbAz-5oyMQcETsuI4o-zjaivRYd3DlqfSx7w562DCPOfT7AE2jXV86yksG-qIbaiquN2Tf7U8FTfy=w408-h305-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 91,
    isOpen: true
  },
  {
    name: 'Brown Riverside',
    description: 'Brown coffee with riverside location',
    tags: ['cafe', 'coffee', 'riverside'],
    facilities: ['WiFi', 'Seating', 'Riverside'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHiGi92FS7wDs9RiRtd6CgeXaPGXgCMO9MFg5JtKS2iuZT6bKnP1084c0wvGgMfQS6ss_8GHTCBJTCgZHJVWIq6WmscvdDv6qxF1TwR3hEQO8EQO790TzdMQV6Czb6rLmX4rHsX=w408-h272-k-no'],
    location: { address: 'Riverside, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 84,
    isOpen: true
  },
  {
    name: 'EURO Coffee & Bakery',
    description: 'European-style bakery and coffee',
    tags: ['bakery', 'coffee', 'european'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'Doi Chaang Coffee Cambodia',
    description: 'Thai specialty coffee brand',
    tags: ['specialty coffee', 'thai'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAE1njVuBVf1R8BU0lcsmlRxYnv5VkYvewxPc_Zd4p1_6xSpc4ljBvL__NnMQHIr3j0-B0LI7ZXZAbIn-kirB0Y0qa4gF0Yzxwy52QyfjCi7reI6z2YiioyTBKbFiag8KGFEugoy=w426-h240-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 77,
    isOpen: true
  },
  {
    name: 'Jom Kopi',
    description: 'Casual coffee shop',
    tags: ['cafe', 'casual'],
    facilities: ['Seating'],
    rating: 3.5,
    priceLevel: 1,
    wifiSpeed: 0,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 60,
    isOpen: true
  },
  {
    name: 'The Corner Restaurant & Bar',
    description: 'Restaurant and bar with cafe options',
    tags: ['restaurant', 'bar', 'cafe'],
    facilities: ['WiFi', 'Seating', 'Bar'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHpG0R8X17zX5kob7YbbeSOxqskqkNLhO8hghddkLj1VZQGY0T1f_nO5P_v_YIvo9K5uBqdMyC5IpTznLZpe3AxOW1TbN-9_XHSSlDR-kygvHCCnNrvBKsccWU0zVIoWigMKtR7=w408-h306-k-no'],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 73,
    isOpen: true
  },
  {
    name: 'Costa Coffee',
    description: 'International coffee chain',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.4,
    priceLevel: 2,
    wifiSpeed: 50,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFQZkF19O8DMXoF2qTCXxLHW4_pKQKXuj3SPI01PCQ4txw-cJvArqFfvk3gq49NweGaCfFpubaR-zs05WTEWy9NXnq-_fwMOF_bhAoeeWfGlkQRXWEPuS5kOMCApzbe3BZWQnLHnQ=w408-h725-k-no'],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 68,
    isOpen: true
  },
  {
    name: 'Gloria Jean\'s Coffees Cambodia',
    description: 'Australian coffee chain',
    tags: ['coffee chain', 'australian'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFlJML8mLPNakwhsBEsDdoU8ObtQ_lqX4-9g1d-JJKyWehHD5K0ea0sRZKCMoH6ONkPBtVZ_ocXlI1zdLzLEVQqsu3-V9cDHyxSxl4Ct0FJE3yXgMVFwWIGT74wJ0TxrwBpfMaT=w408-h306-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'Story Coffee Roasters',
    description: 'Eco-focused specialty coffee roastery',
    tags: ['specialty coffee', 'eco-friendly', 'roastery'],
    facilities: ['Seating'],
    rating: 4.6,
    priceLevel: 2,
    wifiSpeed: 0,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 86,
    isOpen: true
  },
  {
    name: 'Homy Coffee & Tea',
    description: 'Cozy coffee and tea house',
    tags: ['cafe', 'tea', 'cozy'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.9,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFeMq0pwxhiYk6uN4C0rh6D8gO-YimBCKHF32M1JKmOoXg4pOF4NSU-UNFCMsEgHyWaqRDyJ6X2jDEHEK33Fv1-APM9k4MWAf35nAjVM0vIXieHWW0cQW3xSF8C6aR01zA64-dVELERmd0O=w408-h544-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 89,
    isOpen: true
  },
  {
    name: 'Deja Cafe',
    description: 'Modern cafe with international vibes',
    tags: ['cafe', 'modern'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEuLFwYUU2cW8_nnSL00lOj7N-88VRTqY37pkvbR5l-o4GUbxDWB6lMznog1EuvDsTkrVKVqWWOjdxZHZlkRIT8SXMB0mvABofHPCfrAmAeq8bQicFKOYOC7x_kCec_IJ-oTFbg=w408-h408-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 75,
    isOpen: true
  },
  {
    name: 'Kompi Coffee',
    description: 'Neighborhood coffee spot',
    tags: ['cafe', 'neighborhood'],
    facilities: ['Seating'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 0,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 62,
    isOpen: true
  },
  {
    name: 'Deep Blue Cafe',
    description: 'Artistic cafe with blue theme',
    tags: ['cafe', 'artistic'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGql_DAt3hrA4a8UeA1V2dvHh8Q9KFtYdVottDQSrwT7TH_HnRFeY6qie-M61ZEBIgbAhtZCPTrRuqJGpoAelgJwH5DZ9Xbz3wB3e2Ns0rLmm3LNT2hdPYrr100cQb01PkUyDb3kEOJrq8=w408-h544-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 81,
    isOpen: true
  },
  {
    name: 'The Coffee Bean & Tea Leaf (BKK 1)',
    description: 'International coffee chain',
    tags: ['coffee chain', 'international', 'tea'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAECOFGJRUBmH7FiuHBmtmOCrlXTNOJYmqvSi36y3-J8E_qj7vdNfwDe25LsIveOKyUHOleHn4rAH0yAhsTXlX_kP3tYZv71RNRb-Ts5qxthadS0BOw7rBHCgFKpVMgYHsGY4WyPeA=w426-h240-k-no'],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 85,
    isOpen: true
  },
  {
    name: 'Burlap Coffee Factory',
    description: 'Coffee factory and cafe',
    tags: ['cafe', 'factory', 'coffee'],
    facilities: ['Seating', 'Factory Tour'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 60,
    images: [],
    location: { address: 'Chamkar Doung, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 74,
    isOpen: true
  },
  {
    name: 'Daily Drip Coffee Bakery',
    description: 'Coffee and fresh bakery items daily',
    tags: ['bakery', 'coffee', 'daily'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'Arabica Cambodia',
    description: 'Premium arabica coffee experience',
    tags: ['specialty coffee', 'premium'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 85,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHtdyQFUWor6gKYoV7wgabPMX7GuiiFN2GXrQIN8ka-AdZYOTKxHkbKdl71D3Vtcd3DDUF9s59B_zJdBGOrsulrC10fOvSkEVN-CJrcY3UrnlrLhemFEU5YCOWPkG-gl8u7qbLk=w427-h240-k-no'],
    location: { address: 'Vattanac Capital, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'Coffee Today',
    description: 'Contemporary coffee shop',
    tags: ['cafe', 'modern'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 73,
    isOpen: true
  },
  {
    name: 'Kyujitsu X Atmosphere',
    description: 'Japanese matcha cafe',
    tags: ['matcha', 'japanese', 'tea'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.7,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAEfrq-AJJsTc_LZsgY5ACe_2g7mupDIHFvh6k28TOmWf01nT7T0Yjb4cWpyRhKUu-gHH0tTYmVZO_RoNCZQSoxQhmamzJSFvvx9lwa_kWTtERLw8gV51Dkhr5AeO5X_PJ2p8BMp_3V9J5g=w408-h295-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'Dance Bakery & Cafe',
    description: 'Bakery and cafe with creative menu',
    tags: ['bakery', 'cafe', 'creative'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 3.9,
    priceLevel: 2,
    wifiSpeed: 70,
    images: ['https://lh4.googleusercontent.com/GYT_oOQpZPYW53iCQHhhvEn74UEYaIAhEd_26ZZR2nMg80hdpQ2Oyym6yE-wSMoK=w408-h306-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 69,
    isOpen: true
  },
  {
    name: 'Facade Coffee',
    description: 'Stylish modern cafe',
    tags: ['cafe', 'modern', 'stylish'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 81,
    isOpen: true
  },
  {
    name: 'Mister Brew',
    description: 'Craft coffee and brewing',
    tags: ['cafe', 'craft coffee'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 78,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAFrqYZWNFThPTL5Oa4juQ0dgcabcOeT96A6vfoWda8-X8-YgD17BaV5QLs3Dh481wnKNMS81hRE3x9Uzi9FbO6OR_LLjJeUfN8kaQLv1K7gty64W9BZbG6u55YtLApuWByjn_eA=w426-h240-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'Tea Plus Cambodia',
    description: 'Premium tea selection',
    tags: ['tea', 'premium'],
    facilities: ['Seating'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 0,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 65,
    isOpen: true
  },
  {
    name: 'Muteki Coffee Izakaya',
    description: 'Japanese coffee izakaya',
    tags: ['japanese', 'cafe', 'izakaya'],
    facilities: ['WiFi', 'Seating', 'Bar'],
    rating: 4.7,
    priceLevel: 2,
    wifiSpeed: 60,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAGXwACR2OTtQOUh6kH9sbHBZbt1Hqc3oyhhtqrnrM-5P4EENdXJtHtB12IRC1D1JiVBOP1E79aPXerWIelCUUU4NEX1DCF0X-8QZXuoyCHaqCCUjRgZG4AWDIuX-IMq-HeTr30=w408-h725-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'Xotique',
    description: 'Unique and exotic cafe',
    tags: ['cafe', 'exotic'],
    facilities: ['Seating'],
    rating: 3.9,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Toul Tompoung, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 67,
    isOpen: true
  },
  {
    name: 'El Cafetal Colombiano',
    description: 'Authentic Colombian coffee',
    tags: ['specialty coffee', 'colombian', 'latin'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHTMeuOkZPaZFN5X3mtxcrpi4K1TykinKW1cKGnCCtYRdOHy0sSdb5olQoFiR83YP2zE3BbVV8SmgBaXRF1fVVXsI2fhEkODaVM8vwPKCQBYeY9HZOjmCTJB6r-kRwTk_kIdJz53bXuyxTU=w408-h306-k-no'],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'Gather Grounds Coffee & Eatery',
    description: 'Community coffee and eatery',
    tags: ['cafe', 'eatery', 'community'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 77,
    isOpen: true
  },
  {
    name: 'The Alchemist',
    description: 'Specialty coffee and mixology',
    tags: ['specialty coffee', 'bar', 'cafe'],
    facilities: ['WiFi', 'Seating', 'Bar'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 80,
    images: ['https://lh3.googleusercontent.com/gps-cs-s/APNQkAHXq51pCRJRDUPjtrNLKicRMJzgJhJgI1qvbPgS6RYbHIvZhgU6KfYbAZVIFmZKwDWuZzJWAbeFNEuGEufbU6frIWkE3opJaV9bE7fueKCTxf4DIiILe32dyGvOvgPtXwWWbh74=w408-h271-k-no'],
    location: { address: 'Riverside, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'Brown Coffee | BKK1',
    description: 'Popular coffee stop in BKK1',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 88,
    isOpen: true
  },
  {
    name: 'Brown Coffee | Sothearos',
    description: 'Busy Brown branch along Sothearos',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'Sothearos, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 84,
    isOpen: true
  },
  {
    name: 'Brown Coffee | Riverside',
    description: 'Riverside Brown branch for casual meetups',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'Riverside, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'Brown Coffee | Toul Kork',
    description: 'Brown Coffee branch in Toul Kork',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 76,
    images: [],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'Brown Coffee | AEON Mall',
    description: 'Brown inside AEON Mall',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'AEON Mall, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 82,
    isOpen: true
  },
  {
    name: 'Brown Coffee | Olympia',
    description: 'Brown Coffee at Olympia City',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Olympia City, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'Brown Coffee | Vattanac Capital',
    description: 'Central Brown Coffee branch',
    tags: ['coffee chain', 'cafe'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Vattanac Capital, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 87,
    isOpen: true
  },
  {
    name: 'Brown Roastery | TK',
    description: 'Specialty roastery in Toul Kork',
    tags: ['specialty coffee', 'roastery'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 82,
    images: [],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 86,
    isOpen: true
  },
  {
    name: 'Starbucks BKK1',
    description: 'International chain in BKK1',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.2,
    priceLevel: 3,
    wifiSpeed: 75,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 90,
    isOpen: true
  },
  {
    name: 'Starbucks AEON Mall Phnom Penh',
    description: 'Starbucks location in AEON Mall',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.1,
    priceLevel: 3,
    wifiSpeed: 75,
    images: [],
    location: { address: 'AEON Mall, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 88,
    isOpen: true
  },
  {
    name: 'Starbucks Olympia Mall',
    description: 'Starbucks at Olympia Mall',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.1,
    priceLevel: 3,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Olympia City, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 86,
    isOpen: true
  },
  {
    name: 'The Coffee Bean & Tea Leaf | BKK1',
    description: 'Tea and coffee chain spot in BKK1',
    tags: ['coffee chain', 'tea'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 84,
    isOpen: true
  },
  {
    name: 'The Coffee Bean & Tea Leaf | Vattanac Capital',
    description: 'Coffee Bean branch downtown',
    tags: ['coffee chain', 'tea'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.3,
    priceLevel: 3,
    wifiSpeed: 78,
    images: [],
    location: { address: 'Vattanac Capital, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 84,
    isOpen: true
  },
  {
    name: "Gloria Jean's Coffees Cambodia",
    description: 'Popular Gloria Jean branch in Phnom Penh',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'Arabica Cambodia',
    description: 'Premium arabica coffee experience',
    tags: ['specialty coffee', 'premium'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 82,
    images: [],
    location: { address: 'Vattanac Capital, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 88,
    isOpen: true
  },
  {
    name: 'Feel Good Coffee | Norodom',
    description: 'Specialty coffee and pastries',
    tags: ['specialty coffee', 'bakery'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.6,
    priceLevel: 2,
    wifiSpeed: 85,
    images: [],
    location: { address: 'Norodom Blvd, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 92,
    isOpen: true
  },
  {
    name: 'Backyard Cafe | BKK1',
    description: 'Healthy and calm cafe in BKK1',
    tags: ['healthy cafe', 'organic'],
    facilities: ['WiFi', 'Seating', 'Outdoor area'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 85,
    isOpen: true
  },
  {
    name: 'Living Room | Toul Kork',
    description: 'Spacious cafe for work sessions',
    tags: ['cafe', 'relaxing'],
    facilities: ['WiFi', 'Seating', 'Comfortable'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 76,
    images: [],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'Java Creative Cafe | Norodom',
    description: 'Creative cafe with a work-friendly feel',
    tags: ['cafe', 'creative'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 74,
    images: [],
    location: { address: 'Norodom Blvd, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'Java Creative Cafe | Monivong',
    description: 'Java branch near Monivong',
    tags: ['cafe', 'creative'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 74,
    images: [],
    location: { address: 'Monivong Blvd, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'Story Coffee Roasters',
    description: 'Eco-focused specialty coffee roastery',
    tags: ['specialty coffee', 'eco-friendly', 'roastery'],
    facilities: ['Seating'],
    rating: 4.6,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 86,
    isOpen: true
  },
  {
    name: 'WAT Chocolate',
    description: 'Chocolate and cafe experience',
    tags: ['cafe', 'chocolate'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 82,
    isOpen: true
  },
  {
    name: "Cerise's Bakery & Coffee",
    description: 'Bakery with coffee and pastries',
    tags: ['bakery', 'coffee'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.1,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 77,
    isOpen: true
  },
  {
    name: 'Deja Cafe',
    description: 'Modern cafe with an international feel',
    tags: ['cafe', 'modern'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'Gelatofix',
    description: 'Gelato and coffee spot',
    tags: ['cafe', 'gelato'],
    facilities: ['Seating'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 72,
    isOpen: true
  },
  {
    name: 'Coffee Today',
    description: 'Contemporary coffee shop',
    tags: ['cafe', 'modern'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'Doi Chaang Coffee Cambodia',
    description: 'Thai specialty coffee brand',
    tags: ['specialty coffee', 'thai'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'Nuk Cafe',
    description: 'Cozy neighborhood cafe and roastery',
    tags: ['cafe', 'roastery'],
    facilities: ['WiFi', 'Seating', 'Roastery'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'GW Cafe',
    description: 'Casual neighborhood cafe',
    tags: ['cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.8,
    priceLevel: 1,
    wifiSpeed: 60,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 68,
    isOpen: true
  },
  {
    name: 'Homy Coffee & Tea',
    description: 'Cozy coffee and tea house',
    tags: ['cafe', 'tea', 'cozy'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.9,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 90,
    isOpen: true
  },
  {
    name: 'The Barista',
    description: 'Professional barista cafe',
    tags: ['cafe', 'specialty coffee'],
    facilities: ['Seating', 'Professional Coffee'],
    rating: 4.0,
    priceLevel: 2,
    wifiSpeed: 0,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 75,
    isOpen: true
  },
  {
    name: 'The 240',
    description: 'Cafe on the iconic 240 street',
    tags: ['cafe', 'lifestyle'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 72,
    images: [],
    location: { address: 'Street 240, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 81,
    isOpen: true
  },
  {
    name: 'The Shop 240',
    description: 'The Shop branch on Street 240',
    tags: ['cafe', 'bakery'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 74,
    images: [],
    location: { address: 'Street 240, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  },
  {
    name: 'The Shop Toul Kork',
    description: 'The Shop branch in Toul Kork',
    tags: ['cafe', 'bakery'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 72,
    images: [],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'The Shop BKK1',
    description: 'The Shop branch in BKK1',
    tags: ['cafe', 'bakery'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 74,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 81,
    isOpen: true
  },
  {
    name: 'Cafe Amazon BKK1',
    description: 'Cafe Amazon branch in BKK1',
    tags: ['coffee chain', 'thai'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 68,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 70,
    isOpen: true
  },
  {
    name: 'Cafe Amazon AEON Mall',
    description: 'Cafe Amazon branch inside AEON',
    tags: ['coffee chain', 'thai'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 68,
    images: [],
    location: { address: 'AEON Mall, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 69,
    isOpen: true
  },
  {
    name: 'Cafe Amazon TK Avenue',
    description: 'Cafe Amazon at TK Avenue',
    tags: ['coffee chain', 'thai'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 68,
    images: [],
    location: { address: 'Toul Kork, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 68,
    isOpen: true
  },
  {
    name: 'Costa Coffee BKK1',
    description: 'International coffee chain in BKK1',
    tags: ['coffee chain', 'international'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.9,
    priceLevel: 2,
    wifiSpeed: 65,
    images: [],
    location: { address: 'BKK1, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 66,
    isOpen: true
  },
  {
    name: 'La Chronique Cafe & Bistro',
    description: 'French-inspired cafe and bistro',
    tags: ['cafe', 'bistro', 'french'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.7,
    priceLevel: 3,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 72,
    isOpen: true
  },
  {
    name: 'Market Cafe Restaurant & Lounge',
    description: 'Upscale cafe and restaurant lounge',
    tags: ['cafe', 'restaurant'],
    facilities: ['WiFi', 'Seating', 'Lounge'],
    rating: 4.5,
    priceLevel: 3,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 83,
    isOpen: true
  },
  {
    name: 'TWG Tea at Vattanac Mall',
    description: 'Premium tea house',
    tags: ['tea', 'premium'],
    facilities: ['Seating', 'Air conditioning'],
    rating: 4.3,
    priceLevel: 3,
    wifiSpeed: 70,
    images: [],
    location: { address: 'Vattanac Mall, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 77,
    isOpen: true
  },
  {
    name: 'Khmer Flower House Cafe',
    description: 'Traditional Khmer cafe with flowers',
    tags: ['cafe', 'khmer', 'cultural'],
    facilities: ['Seating', 'Garden'],
    rating: 4.9,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 91,
    isOpen: true
  },
  {
    name: 'Brown Riverside',
    description: 'Brown coffee with riverside location',
    tags: ['cafe', 'coffee', 'riverside'],
    facilities: ['WiFi', 'Seating', 'Riverside'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Riverside, Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 84,
    isOpen: true
  },
  {
    name: 'EURO Coffee & Bakery',
    description: 'European-style bakery and coffee',
    tags: ['bakery', 'coffee', 'european'],
    facilities: ['WiFi', 'Seating', 'Bakery'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 76,
    isOpen: true
  },
  {
    name: 'The Ground Phnom Penh',
    description: 'Minimal coffee bar with a calm vibe',
    tags: ['cafe', 'modern'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 74,
    isOpen: true
  },
  {
    name: 'U & Me Coffee',
    description: 'Casual cafe for everyday meetups',
    tags: ['cafe', 'casual'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.1,
    priceLevel: 1,
    wifiSpeed: 65,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 67,
    isOpen: true
  },
  {
    name: 'Little Paris Cafe',
    description: 'Paris-inspired cafe with pastry focus',
    tags: ['cafe', 'bakery', 'french'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 72,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 74,
    isOpen: true
  },
  {
    name: 'Aroma Cafe',
    description: 'Everyday cafe with simple comforts',
    tags: ['cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 65,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 65,
    isOpen: true
  },
  {
    name: 'Mister B Cafe',
    description: 'Friendly neighborhood coffee stop',
    tags: ['cafe'],
    facilities: ['WiFi', 'Seating'],
    rating: 3.9,
    priceLevel: 1,
    wifiSpeed: 60,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 64,
    isOpen: true
  },
  {
    name: 'The Coffee House',
    description: 'Comfortable cafe for long visits',
    tags: ['cafe', 'comfort'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.2,
    priceLevel: 2,
    wifiSpeed: 75,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 75,
    isOpen: true
  },
  {
    name: 'Sips and Stories',
    description: 'Quiet reading-friendly cafe',
    tags: ['cafe', 'quiet'],
    facilities: ['WiFi', 'Seating', 'Quiet atmosphere'],
    rating: 4.5,
    priceLevel: 2,
    wifiSpeed: 80,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 78,
    isOpen: true
  },
  {
    name: 'Urban Space Cafe',
    description: 'Modern work-friendly cafe space',
    tags: ['cafe', 'work-friendly'],
    facilities: ['WiFi', 'Seating', 'Air conditioning'],
    rating: 4.3,
    priceLevel: 2,
    wifiSpeed: 78,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 79,
    isOpen: true
  },
  {
    name: 'Bean There Cafe',
    description: 'Casual coffee spot with good atmosphere',
    tags: ['cafe', 'casual'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.0,
    priceLevel: 1,
    wifiSpeed: 66,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 63,
    isOpen: true
  },
  {
    name: 'Mornings Coffee',
    description: 'Morning-focused cafe with pastries',
    tags: ['cafe', 'breakfast'],
    facilities: ['WiFi', 'Seating'],
    rating: 4.1,
    priceLevel: 1,
    wifiSpeed: 68,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 64,
    isOpen: true
  },
  {
    name: 'The Hive Cafe',
    description: 'Community-oriented cafe and workspace',
    tags: ['cafe', 'community', 'workspace'],
    facilities: ['WiFi', 'Seating', 'Study-friendly'],
    rating: 4.4,
    priceLevel: 2,
    wifiSpeed: 82,
    images: [],
    location: { address: 'Phnom Penh', coords: { lat: 0, lng: 0 } },
    popularity: 80,
    isOpen: true
  }
];

async function seed(){
  const { sequelize, Cafe, User } = require('./models');
  // Do not force-drop tables on hosted DBs; create missing tables only
  await sequelize.sync();

  const buildGoogleMapsUrl = (name, address) => {
    const query = [name, address || 'Phnom Penh'].filter(Boolean).join(' ')
    return `https://www.google.com/maps/search/${encodeURIComponent(query)}`
  }

  const localCafeImages = [
    '/images/cafe-placeholder-1.svg',
    '/images/cafe-placeholder-2.svg',
    '/images/cafe-placeholder-3.svg',
    '/images/cafe-placeholder-4.svg'
  ]

  const pickLocalCafeImage = (name) => {
    const value = String(name || 'Cafe')
    let hash = 0
    for (let index = 0; index < value.length; index += 1) {
      hash = (hash * 31 + value.charCodeAt(index)) >>> 0
    }
    return localCafeImages[hash % localCafeImages.length]
  }

  // Helper: only keep entries that look like direct image URLs
  const isLikelyImage = (u) => {
    if (!u || typeof u !== 'string') return false;
    return /(\.(jpeg|jpg|png|gif|webp|svg|bmp))(?:\?|$)/i.test(u)
      || u.includes('lh3.googleusercontent.com')
      || u.includes('lh4.googleusercontent.com')
      || u.includes('lh5.googleusercontent.com');
  }

  // Create or update cafes (idempotent)
  for (let index = 0; index < sample.length; index += 1) {
    const s = sample[index];
    const values = {
      name: s.name,
      description: s.description,
      tags: Array.from(new Set([
        ...(s.tags || []),
        ...(s.wifiSpeed >= 70 ? ['Fast WiFi'] : []),
        ...(s.rating >= 4.5 ? ['Top Rated'] : []),
        ...(s.facilities || []).some((facility) => /outdoor/i.test(facility)) ? ['Outdoor seating'] : [],
        ...(s.facilities || []).some((facility) => /air conditioning/i.test(facility)) ? ['Air conditioning'] : []
      ])),
      facilities: Array.from(new Set([
        ...(s.facilities || []),
        'Study-friendly',
        ...(s.wifiSpeed >= 70 ? ['Fast WiFi'] : []),
        ...(s.rating >= 4.5 ? ['Quiet atmosphere'] : [])
      ])),
      rating: s.rating,
      priceLevel: s.priceLevel,
      wifiSpeed: s.wifiSpeed,
      images: (s.images || []).some((image) => String(image || '').startsWith('/images/'))
        ? (s.images || []).filter((image) => String(image || '').startsWith('/images/'))
        : [pickLocalCafeImage(s.name || `Cafe ${index + 1}`)],
      location: {
        ...(s.location || {}),
        googleMapsUrl: buildGoogleMapsUrl(s.name, s.location?.address)
      },
      popularity: s.popularity,
      isOpen: s.isOpen,
      openingHours: s.openingHours || {
        Mon: '8:00 AM - 10:00 PM',
        Tue: '8:00 AM - 10:00 PM',
        Wed: '8:00 AM - 10:00 PM',
        Thu: '8:00 AM - 10:00 PM',
        Fri: '8:00 AM - 10:00 PM',
        Sat: '8:00 AM - 11:00 PM',
        Sun: '8:00 AM - 11:00 PM'
      }
    };

    const existing = await Cafe.findOne({ where: { name: s.name } });
    if (existing) {
      await existing.update(values);
    } else {
      await Cafe.create(values);
    }
  }

  // Upsert admin and demo users by email
  const adminPassword = await bcrypt.hash('admin123', 10);
  await User.upsert({
    name: 'Admin',
    email: 'admin@caferecs.com',
    password: adminPassword,
    role: 'admin'
  });

  const demoPassword = await bcrypt.hash('user123', 10);
  await User.upsert({
    name: 'Demo Student',
    email: 'demo@caferecs.com',
    password: demoPassword,
    role: 'user',
    preferences: {
      tags: ['study-friendly', 'Fast WiFi', 'Quiet'],
      pricePref: 2
    }
  });

  console.log('Seeded cafes, demo user, and admin user');
  process.exit();
}

seed().catch(e=>{console.error(e); process.exit(1)});
